version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  migration:
    aliases:
      - migrate
    desc: "Run database migrations"
    cmds:
      - go run ../sso/cmd/migrator/main.go --storage-path=../sso/storage/sso.db --migrations-path=../sso/migrations