version: '3'

tasks:
  generate:
    aliases:
      -gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

    tasks:
      generate:
        aliases:
          -make migration
        desc: "Generate code from proto files"
        cmds:
          - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
